# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources and Function App
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: 3.bicep.build.deploy
run-name: '3 - Bicep/Build/Deploy Apps using ENV ${{ inputs.deployEnvironment }} ${{vars.INSTANCE_NUMBER}} by @${{ github.actor }}'
on: 
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        default: 'dev' 
        type: environment
      createResourceGroup:
        description: Create Resource Group?
        type: boolean
        default: true
      runCreateInfra:
        description: Deploy Bicep
        default: true
        type: boolean
      logicAppAction:
        description: Logic App
        default: deploy 
        type: choice
        options:
          - ignore
          - build
          - deploy 
      functionAppAction:
        description: Function
        default: deploy 
        type: choice
        options:
          - ignore
          - build
          - deploy
      runSecurityScan:
        description: Run Security Scan
        default: false
        type: boolean
      runDeployCosmos:
        description: Update Cosmos DB
        default: True
        type: boolean
      # runSmokeTest:
      #   description: Run Smoke Tests
      #   default: false
      #   type: boolean

# ------------------------------------------------------------------------------------------------------------------------
permissions:
  id-token: write
  contents: write
  actions: read
  pages: write
  security-events: write
  checks: write
  issues: read
  pull-requests: read
  packages: read

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  # load the project configuration variables once for all jobs
  load-config:
    uses: ./.github/workflows/template-load-config.yml

  # ------------------------------------------------------------------------------------------------------------------------
  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template-scan-code.yml
    secrets: inherit
    if: inputs.runSecurityScan
    with:
      runMSDevSecOpsScan: ${{ inputs.runSecurityScan }}
      runGHASScan: ${{ inputs.runSecurityScan }}

  # ------------------------------------------------------------------------------------------------------------------------
  create-infra:
    name: Create Infra ${{ inputs.deployEnvironment }}
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      runCreateInfra: ${{ inputs.runCreateInfra }}
      envCode: ${{ inputs.deployEnvironment }}
      templatePath: './infra/Bicep/'
      templateFile: 'main.bicep'
      parameterFile: 'main.gha.bicepparam'
      parameterFileReplaceTokens: 'true'
      requestorName: ${{ github.actor }}
      createResourceGroup: ${{ inputs.createResourceGroup }}
      deployCosmos: ${{ inputs.runDeployCosmos }}

# ------------------------------------------------------------------------------------------------------------------------
  build-intake-function:
    name: Build Intake Function App
    uses: ./.github/workflows/template-function-app-build.yml
    if: inputs.functionAppAction != 'ignore'
    needs: [load-config, create-infra]
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      rootDirectory: ${{ needs.load-config.outputs.intake_rootDirectory }}
      projectName: ${{ needs.load-config.outputs.intake_projectName }}
      testDirectory: ${{ needs.load-config.outputs.intake_testDirectory }}
      testProjectName: ${{ needs.load-config.outputs.intake_testProjectName }}
      functionSubName:  ${{ needs.load-config.outputs.intake_shortName }}
      testApplication: true
      listFilesAfterBuild: true

  deploy-intake-function:
    name: Deploy Intake Function
    uses: ./.github/workflows/template-function-app-deploy.yml
    if: inputs.functionAppAction == 'deploy'
    needs: [load-config, build-intake-function]
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      functionSubName: ${{ needs.load-config.outputs.intake_shortName }}
      listFilesBeforeDeploy: true

# # ------------------------------------------------------------------------------------------------------------------------
#   build-processor-function:
#     name: Build processor Function App
#     uses: ./.github/workflows/template-function-app-build.yml
#     if: inputs.functionAppAction != 'ignore'
#     needs: [load-config, deploy-intake-function]
#     secrets: inherit
#     with:
#       envCode: ${{ inputs.deployEnvironment }}
#       rootDirectory: ${{ needs.load-config.outputs.processor_rootDirectory }}
#       projectName: ${{ needs.load-config.outputs.processor_projectName }}
#       testDirectory: ${{ needs.load-config.outputs.processor_testDirectory }}
#       testProjectName: ${{ needs.load-config.outputs.processor_testProjectName }}
#       functionSubName: ${{ needs.load-config.outputs.processor_shortName }}
#       testApplication: true
#       listFilesAfterBuild: true

#   deploy-processor-function:
#     name: Deploy processor Function
#     uses: ./.github/workflows/template-function-app-deploy.yml
#     if: inputs.functionAppAction == 'deploy'
#     # the login seems to crash if you try to deploy both web and function at the same time...???
#     needs: build-processor-function
#     secrets: inherit
#     with:
#       envCode: ${{ inputs.deployEnvironment }}
#       functionSubName: ${{ needs.load-config.outputs.processor_shortName }}
#       listFilesBeforeDeploy: true
      
# ------------------------------------------------------------------------------------------------------------------------
  build-acceptor-function:
    name: Build Acceptor Function App
    uses: ./.github/workflows/template-function-app-build.yml
    if: inputs.functionAppAction != 'ignore'
    secrets: inherit
    needs: [load-config]
    with:
      envCode: ${{ inputs.deployEnvironment }}
      rootDirectory: ${{ needs.load-config.outputs.acceptor_rootDirectory }}
      projectName: ${{ needs.load-config.outputs.acceptor_projectName }}
      testDirectory: ${{ needs.load-config.outputs.acceptor_testDirectory }}
      testProjectName: ${{ needs.load-config.outputs.acceptor_testProjectName }}
      functionSubName: ${{ needs.load-config.outputs.acceptor_shortName }}
      testApplication: true
      listFilesAfterBuild: true

  deploy-acceptor-function:
    name: Deploy Acceptor Function App ${{ inputs.deployEnvironment }}
    uses: ./.github/workflows/template-function-app-deploy.yml
    if: inputs.functionAppAction == 'deploy'
    needs: [load-config, build-acceptor-function]
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      functionSubName: ${{ needs.load-config.outputs.acceptor_shortName }}
      listFilesBeforeDeploy: true

# # ------------------------------------------------------------------------------------------------------------------------
#   run-smoke-test:
#     name: Smoke Test ${{ inputs.deployEnvironment }}
#     uses: ./.github/workflows/template-smoke-test.yml
#     if: inputs.runSmokeTest
#     needs: deploy-intake-function
#     secrets: inherit
#     with:
#       envCode: ${{ inputs.deployEnvironment }}
#       testPath: 'playwright/function-tests'
#       testType: 'function'
