# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources and WebApp and Function
# ------------------------------------------------------------------------------------------------------------------------
# FYI: You need to set up some secrets before running this workflows - see CreateGitHubSecrets.md for details.
# ------------------------------------------------------------------------------------------------------------------------
name: 3.build.deploy
run-name: '3 - [${{ inputs.deployEnvironment }}] Build/Deploy by @${{ github.actor }}'

on: 
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        default: 'dev' 
        type: environment
      runSecurityScan:
        description: Run Security Scan
        default: false
        type: boolean
      runBuildDeployLogicApp:
        description: Build and Deploy Logic App
        default: true
        type: boolean
      runBuildDeployFunction:
        description: Build and Deploy Function
        default: true
        type: boolean
      logLevel:
        description: Log level
        required: false
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

# ------------------------------------------------------------------------------------------------------------------------
permissions:
  id-token: write
  contents: write
  actions: read
  pages: write
  security-events: write
  checks: write
  issues: read
  pull-requests: read
  packages: read

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template-scan-code.yml
    secrets: inherit
    if: inputs.runSecurityScan
    with:
      runMSDevSecOpsScan: ${{ inputs.runSecurityScan }}
      runGHASScan: ${{ inputs.runSecurityScan }}

# ------------------------------------------------------------------------------------------------------------------------
  build-logicapp:
    name: Build Logic App
    uses: ./.github/workflows/template-webapp-build.yml
    if: inputs.runBuildDeployLogicApp
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      rootDirectory: '${{ vars.ACCEPTOR_PROJECT_FOLDER_NAME }}'
      projectName: '${{ vars.ACCEPTOR_PROJECT_NAME }}'
      testDirectory: '${{ vars.ACCEPTOR_TEST_FOLDER_NAME }}'
      testProjectName: '${{ vars.ACCEPTOR_TEST_PROJECT_NAME }}'
      testApplication: true
      listFilesAfterBuild: true

  build-func:
    name: Build Function
    if: inputs.runBuildDeployFunction
    uses: ./.github/workflows/template-function-app-build.yml
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      rootDirectory: '${{ vars.INTAKE_PROJECT_FOLDER_NAME }}'
      projectName: '${{ vars.INTAKE_PROJECT_NAME }}'
      testDirectory: '${{ vars.INTAKE_TEST_FOLDER_NAME }}'
      testProjectName: '${{ vars.INTAKE_TEST_PROJECT_NAME }}'
      testApplication: true
      listFilesAfterBuild: true

# ------------------------------------------------------------------------------------------------------------------------
  deploy-logicapp:
    name: Deploy LogicApp ${{ inputs.deployEnvironment }}
    uses: ./.github/workflows/template-webapp-deploy.yml
    if: inputs.runBuildDeployLogicApp
    needs: [ build-logicapp ]
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      listFilesBeforeDeploy: true

  deploy-func:
    name: Deploy Function
    # the login seems to crash if you try to deploy both web and function at the same time...???
    needs: [ build-func ]
    uses: ./.github/workflows/template-function-app-deploy.yml
    if: inputs.runBuildDeployFunction
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      functionType: 'flex'
      listFilesBeforeDeploy: true
